// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Activity;
using ApiSdk.Health;
using ApiSdk.Heartbeat;
using ApiSdk.Metrics;
using ApiSdk.Vaults;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OnePasswordConnectClient : BaseRequestBuilder
    {
        /// <summary>The activity property</summary>
        public global::ApiSdk.Activity.ActivityRequestBuilder Activity
        {
            get => new global::ApiSdk.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::ApiSdk.Health.HealthRequestBuilder Health
        {
            get => new global::ApiSdk.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The heartbeat property</summary>
        public global::ApiSdk.Heartbeat.HeartbeatRequestBuilder Heartbeat
        {
            get => new global::ApiSdk.Heartbeat.HeartbeatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::ApiSdk.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::ApiSdk.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vaults property</summary>
        public global::ApiSdk.Vaults.VaultsRequestBuilder Vaults
        {
            get => new global::ApiSdk.Vaults.VaultsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.OnePasswordConnectClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OnePasswordConnectClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://localhost:8080/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
